only allow 'retrace' user to access tasks

diff --git a/retrace-server.spec.in b/retrace-server.spec.in
--- a/retrace-server.spec.in
+++ b/retrace-server.spec.in
@@ -68,15 +68,12 @@ exit 0
 
 %post
 /sbin/install-info %{_infodir}/%{name} %{_infodir}/dir 2> /dev/null || :
-/usr/sbin/usermod -a -G mock apache 2> /dev/null || :
+/usr/sbin/usermod -a -G mock retrace 2> /dev/null || :
 
 if [ "$1" = 1 ]
 then
-#add disabled crontab entry to apache's crontab
-    %define apache_crontab_entry "# 0 * * * * /usr/bin/retrace-server-cleanup >> /var/log/retrace-server/cleanup_error.log 2>&1"
-    (crontab -u apache -l 2> /dev/null; echo %{apache_crontab_entry}) | crontab -u apache - 2> /dev/null
-
 #add disabled crontab entries to retrace's crontab
+    %define retrace_crontab_entry0 "# 0 * * * * /usr/bin/retrace-server-cleanup >> /var/log/retrace-server/cleanup_error.log 2>&1"
     %define retrace_crontab_entry1 "#0 0,12 * * * /usr/bin/retrace-server-reposync fedora 15 i386 >> /var/log/retrace-server/reposync_error.log 2>&1"
     %define retrace_crontab_entry2 "#0 2,14 * * * /usr/bin/retrace-server-reposync fedora 15 x86_64 >> /var/log/retrace-server/reposync_error.log 2>&1"
     %define retrace_crontab_entry3 "#0 4,16 * * * /usr/bin/retrace-server-reposync fedora 16 i386 >> /var/log/retrace-server/reposync_error.log 2>&1"
@@ -84,7 +81,7 @@ then
     %define retrace_crontab_entry5 "#0 8,20 * * * /usr/bin/retrace-server-reposync fedora rawhide i386 >> /var/log/retrace-server/reposync_error.log 2>&1"
     %define retrace_crontab_entry6 "#0 10,22 * * * /usr/bin/retrace-server-reposync fedora rawhide x86_64 >> /var/log/retrace-server/reposync_error.log 2>&1"
 
-    (crontab -u retrace -l 2> /dev/null; \
+    (crontab -u retrace -l 2> /dev/null; echo %{retrace_crontab_entry0}; \
      echo %{retrace_crontab_entry1}; echo %{retrace_crontab_entry2}; \
      echo %{retrace_crontab_entry3}; echo %{retrace_crontab_entry4}; \
      echo %{retrace_crontab_entry5}; echo %{retrace_crontab_entry6};) | crontab -u retrace - 2> /dev/null
@@ -94,8 +91,6 @@ fi
 if [ "$1" = 0 ]
 then
     /sbin/install-info --delete %{_infodir}/retrace-server %{_infodir}/dir 2> /dev/null || :
-#remove retrace-server related entries from apache's crontab
-    (crontab -u apache -l 2> /dev/null | grep -v "%{name}") | crontab -u apache - 2> /dev/null
 
 #comment entries in retrace's crontab
     (crontab -u retrace -l 2> /dev/null | sed "s,^\([^#].*\)$,#\1,g") | crontab -u retrace - 2> /dev/null
@@ -107,9 +102,9 @@ fi
 %config(noreplace) %{_sysconfdir}/%{name}.conf
 %config(noreplace) %{_sysconfdir}/logrotate.d/%{name}
 %dir %attr(0755,retrace,retrace) %{_localstatedir}/cache/%{name}
-%dir %attr(0775,retrace,apache) %{_localstatedir}/cache/%{name}/kernel
-%dir %attr(0775,retrace,apache) %{_localstatedir}/log/%{name}
-%dir %attr(0775,retrace,apache) %{_localstatedir}/spool/%{name}
+%dir %attr(0755,retrace,retrace) %{_localstatedir}/cache/%{name}/kernel
+%dir %attr(0750,retrace,retrace) %{_localstatedir}/log/%{name}
+%dir %attr(0750,retrace,retrace) %{_localstatedir}/spool/%{name}
 %dir %{_datadir}/%{name}
 %{_bindir}/%{name}-worker
 %{_bindir}/%{name}-interact
